# 2.配置相关信息
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/onlinemusic?useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=GMT
#    username: root
#    password: admin
#    type: com.alibaba.druid.pool.DruidDataSource

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/onlinemusic?useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=GMT
      username: root
      password: admin