country: china
province: beijing
city: beijing
area: haidian

port: 8080

user2:
  name: mjn
  age: 22

likes:
  - game
  - music
  - sleep

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 17

user3: [{name: zhangsan, age: 18}, {name: lisi, age: 17}]

baseDir: c:\windows10

# 使用${属性名}引用数据
tempDir: ${baseDir}\temp

# 显示特殊字符制表位 \t
# 使用引号包裹的字符串，其中的转义字符可以生效
tmpDir: "${baseDir}\tmp\t1\t2\t3"

server:
  port: 80

# 创建类，用于封装下面的数据
# 由Spring帮我们去加载数据到对象中，一定要告诉Spring加载这组信息
# 使用的时候从Spring中直接获取信息使用

datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: root666